name: Run Docker Container with VNC

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Docker Container
      run: |
        docker run -d -it --rm -p 6080:80 --shm-size 2g -e ALSADEV=hw:2,0 dorowu/ubuntu-desktop-lxde-vnc

    - name: Sleep for a while to let container start
      run: sleep 30

    - name: Get container IP
      id: container_ip
      run: echo "::set-output name=ip::$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -q))"

    - name: Print container IP
      run: echo "Container IP Address - ${{ steps.container_ip.outputs.ip }}"
