name: Run Docker Container with VNC

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Install sshpass for SSH tunneling
    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    # Install Docker CLI
    - name: Install Docker CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        sudo apt-get update
        sudo apt-get install -y docker-ce

    # Get the ID or name of the running container
    - name: Get Container ID or Name
      id: get_container_id_or_name
      run: |
        CONTAINER_ID_OR_NAME=$(docker ps --format "{{.ID}}")
        echo "::set-output name=container_id_or_name::$CONTAINER_ID_OR_NAME"

    # Get the IP address of the running container
    - name: Get Container IP
      id: get_container_ip
      run: |
        CONTAINER_ID_OR_NAME=${{ steps.get_container_id_or_name.outputs.container_id_or_name }}
        CONTAINER_IP=$(docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $CONTAINER_ID_OR_NAME)
        echo "::set-output name=container_ip::$CONTAINER_IP"

    # Print Container IP
    - name: Print Container IP
      run: echo "Container IP Address - ${{ steps.get_container_ip.outputs.container_ip }}"
