name: Run Docker Container with VNC

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Docker Container
      run: |
        docker run -d -it --rm -p 6080:80 --shm-size 2g -e ALSADEV=hw:2,0 dorowu/ubuntu-desktop-lxde-vnc

    - name: Sleep for a while to let container start
      run: sleep 30

    - name: Get Public IP
      id: get_public_ip
      run: |
        PUBLIC_IP=$(curl -s https://ifconfig.me/ip)
        echo "::set-output name=public_ip::$PUBLIC_IP"

    - name: Print Public IP
      run: echo "Public IP Address - ${{ steps.get_public_ip.outputs.public_ip }}"
