name: Run Docker Container with VNC

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Install sshpass for SSH tunneling
    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    # Install Docker CLI
    - name: Install Docker CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        sudo apt-get update
        sudo apt-get install -y docker-ce

    # Get the ID or name of the running container
    - name: Get Container ID or Name
      id: get_container_id_or_name
      run: |
        CONTAINER_ID_OR_NAME=$(docker ps --format "{{.ID}}")
        echo "::set-output name=container_id_or_name::$CONTAINER_ID_OR_NAME"

    # Get the IP address of the running container
    - name: Get Container IP
      id: get_container_ip
      run: |
        CONTAINER_IP=$(docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ${{ steps.get_container_id_or_name.outputs.container_id_or_name }})
        echo "::set-output name=container_ip::$CONTAINER_IP"

    # Get public IP address
    - name: Get Public IP
      id: get_public_ip
      run: |
        PUBLIC_IP=$(curl -s https://ifconfig.me/ip)
        echo "::set-output name=public_ip::$PUBLIC_IP"

    # SSH Tunneling
    - name: SSH Tunneling
      run: |
        echo "Intermediary Server IP: user@${{ steps.get_container_ip.outputs.container_ip }}"
        echo "Public IP Address: ${{ steps.get_public_ip.outputs.public_ip }}"
        sshpass -p 'your_password' ssh -o StrictHostKeyChecking=no user@${{ steps.get_container_ip.outputs.container_ip }} -NL 5901:localhost:5901

    # Print Container IP
    - name: Print Container IP
      run: echo "Container IP Address - ${{ steps.get_container_ip.outputs.container_ip }}"
