name: Run Docker Container with VNC and SSH

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Install sshpass for SSH tunneling
    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    # Install Docker CLI
    - name: Install Docker CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        sudo apt-get update
        sudo apt-get install -y docker-ce

    # Run the Docker container with VNC and SSH and get its ID
    - name: Run Docker Container with VNC and SSH and Get ID
      id: run_container
      run: |
        docker run -d -it --rm -p 5901:5901 -p 2222:22 --shm-size 2g -e ALSADEV=hw:2,0 -e VNC_PW=meo dorowu/ubuntu-desktop-lxde-vnc bash -c "apt-get update && apt-get install -y openssh-server && service ssh start && /bin/bash"
        CONTAINER_ID=$(docker ps --format "{{.ID}}")
        echo "::set-output name=container_id::$CONTAINER_ID"

    # Get the IP address of the running container
    - name: Get Container IP
      id: get_container_ip
      run: |
        CONTAINER_ID=${{ steps.run_container.outputs.container_id }}
        CONTAINER_IP=$(docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $CONTAINER_ID)
        echo "::set-output name=container_ip::$CONTAINER_IP"

    # SSH Tunneling
    - name: SSH Tunneling
      run: |
        sshpass -p 'your_password' ssh -o StrictHostKeyChecking=no -p 2222 user@${{ steps.get_container_ip.outputs.container_ip }} -NL 5901:localhost:5901

    # Print Container IP
    - name: Print Container IP
      run: echo "Container IP Address - ${{ steps.get_container_ip.outputs.container_ip }}"
