version: "3"

services:
  app:
    image: dorowu/ubuntu-desktop-lxde-vnc
    ports:
      - "6080:80"
    environment:
      - ALSADEV=hw:2,0
    shm_size: "2g"
    restart: "always"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
