version: "3"

services:
  app:
    image: dorowu/ubuntu-desktop-lxde-vnc
    ports:
      - "6080:80"
    environment:
      - ALSADEV=hw:2,0
    shm_size: "2g"
    restart: "always"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix

workflows:
  start-docker:
    jobs:
      - start-app:
          type: "service"
          service: "app"

    triggers:
      - manual: {}
