name: Build and Run TrustDesk Container

on:
  push:
    branches:
      - main

jobs:
  build_and_run_container:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t ubuntu_trustdesk .

    - name: Run Docker container
      run: docker run -d --name trustdesk_container ubuntu_trustdesk

    - name: Get TrustDesk ID and Password
      run: |
        sleep 10 # Wait for TrustDesk to initialize
        TRUSTDESK_ID=$(docker exec trustdesk_container trustdesk get-id)
        TRUSTDESK_PASSWORD=$(docker exec trustdesk_container trustdesk get-password)
        echo "TrustDesk ID: $TRUSTDESK_ID"
        echo "TrustDesk Password: $TRUSTDESK_PASSWORD"
